### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by Bezerragrasi** [patricia-ternes/patricia-ternes.github.io#4]
Hi,

I really liked your webpage and I'm thinking of using it as template, but for my page, I also need a *Contact Form*.
Do you know if it would be possible to integrate this in your template (using gh-pages and Jekkyl)?

Many thanks

**Comment by patricia-ternes** [comment]
Hi @Bezerragrasi 

Glad you liked my page. I would be very happy if you used it as a template, just remember to include all credits.

About the contact form, the solution is not so straightforward because it would need `PHP` - which as far as I know doesn't integrate well with `gh-pages`. But there are simple tools that make it possible to create forms. You can see my [github-pages_form][1] repository on this subject.

This would be a feature I would like to have on my webpage, but at the moment I don't have time to implement it. If you want to play around and do a PR I'm happy to review/approve.

[1]: https://github.com/patricia-ternes/github-pages_form

**Comment by Bezerragrasi** [comment]
Thank you for your reply.

The [github-pages_form](https://github.com/patricia-ternes/github-pages_form) solution is very good.
I will use this and do the PR
